site: 
  title: My Road to be a better dev
  url: https://0k1745.github.io/roadmap/
  start_page: root::index.adoc
content:
  sources:
    - url: ./
      start_path: docs/
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: false
  supplemental_files: ./docs/supplemental-ui
