site: 
  title: My Road to be a better dev
  url: http://localhost:8080
  start_page: root::index.adoc
content:
  sources:
    - url: ./
      start_path: docs/
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
