name: Publish to GitHub Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
  packages: write
concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  build-gui:
    uses: ./.github/actions/deploy-docker@main
    with:
      contextPath: app/processus
  build-process:
    uses: ./.github/actions/deploy-docker@main
    with:
      contextPath: app/home

